### ISSUE TITLE
Supplying the --rf option causes a TypeError to occur

### ISSUE THREAD

**Issue by SMyrick98** [oxygenhq/oxygen#283]
In the latest version of oxygen-cli, supplying a value for the --rf option causes a TypeError in cli-utils.js, as seen in the stacktrace below:

uncaughtException TypeError: Cannot read property 'reporters' of undefined
    at Object.getConfigurations (C:\Users\smyrick\AppData\Roaming\npm\node_modules\oxygen-cli\src\lib\cli-util.js:187:89)
    at Object.<anonymous> (C:\Users\smyrick\AppData\Roaming\npm\node_modules\oxygen-cli\src\lib\cli.js:50:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

If I'm not mistaken, this issue began in v1.28.0, and the line that throws the error is the following:

if ((!projConfigOpts.reporting && !cmdOpts.reporting) || (!**projConfigOpts.reporting.reporters** && !cmdOpts.reporting)) {

The option being used is --rf='html,json', which is working on an older version (1.19.1 - we're trying to update our automation tools but our current scripts break due to this issue). The issue does not occur when using an oxygen.conf file.

**Comment by romovs** [comment]
This has been fixed in v1.30.3.

Thanks for the report!
